name: SDK publish dry run

on:
  workflow_dispatch:
  push:
    branches:
      - 'publish-dry-run/**'

permissions:
  contents: read

jobs:
  dry-run-publish:
    runs-on: ubuntu-latest
    name: ${{ matrix.package }} dry-run
    strategy:
      matrix:
        package:
          - mindbox_platform_interface
          - mindbox_android
          - mindbox_ios
          - mindbox
      fail-fast: false

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          channel: stable

      - name: Dry run publish
        uses: sakebook/actions-flutter-pub-publisher@150ed867828c76c47814ff8bcdfe936273ff7fd1 # v1.21
        with:
          package_directory: ${{ matrix.package }}
          credential: ${{ secrets.PUB_CREDENTIALS }}
          flutter_package: true
          skip_test: true
          dry_run: true
