name: SDK publish dry run

on:
  workflow_dispatch:
  push:
    branches:
      - 'publish-dry-run/**'

permissions:
  contents: read

jobs:
  dry-run-publish:
    runs-on: ubuntu-latest
    name: ${{ matrix.package }} dry-run
    strategy:
      matrix:
        package:
          - mindbox_platform_interface
          - mindbox_android
          - mindbox_ios
          - mindbox
      fail-fast: false

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          channel: stable

      - name: Dry run publish
        uses: sakebook/actions-flutter-pub-publisher@7112915a1a834881d4c98ef7af12f3456e5c79c7 # v1.3.1
        with:
          package_directory: ${{ matrix.package }}
          credential: ${{ secrets.PUB_CREDENTIALS }}
          flutter_package: true
          skip_test: true
          dry_run: true
